In [58]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [59]:
df = pd.read_csv(r"C:\Machine learning\NLP\Emotions_Detection_NLP_ML\backend\data\train.txt",sep =';',names=["texts","emotions"],header=None)

In [60]:
df.head()

                                               texts emotions
0                            i didnt feel humiliated  sadness
1  i can go from feeling so hopeless to so damned...  sadness
2   im grabbing a minute to post i feel greedy wrong    anger
3  i am ever feeling nostalgic about the fireplac...     love
4                               I am feeling grouchy    anger

In [61]:
df.isnull().sum()

texts       0
emotions    0
dtype: int64

In [62]:
unique_emotions = df['emotions'].unique()
emotion_number = {}

i=0
for emo in unique_emotions:
    emotion_number[emo]=i
    i += 1

df['emotions'] = df['emotions'].map(emotion_number)

In [63]:
df

                                                   texts  emotions
0                                i didnt feel humiliated         0
1      i can go from feeling so hopeless to so damned...         0
2       im grabbing a minute to post i feel greedy wrong         1
3      i am ever feeling nostalgic about the fireplac...         2
4                                   I am feeling grouchy         1
...                                                  ...       ...
15995  i just had a very brief time in the beanbag an...         0
15996  i am now turning and i feel pathetic that i am...         0
15997                     i feel strong and good overall         5
15998  i feel like this was such a rude comment and i...         1
15999  i know a lot but i feel so stupid because i ca...         0

[16000 rows x 2 columns]

In [64]:
df['texts'] = df['texts'].str.lower()

In [65]:
df.head(10)

                                               texts  emotions
0                            i didnt feel humiliated         0
1  i can go from feeling so hopeless to so damned...         0
2   im grabbing a minute to post i feel greedy wrong         1
3  i am ever feeling nostalgic about the fireplac...         2
4                               i am feeling grouchy         1
5  ive been feeling a little burdened lately wasn...         0
6  ive been taking or milligrams or times recomme...         3
7  i feel as confused about life as a teenager or...         4
8  i have been with petronas for years i feel tha...         5
9                                i feel romantic too         2

In [66]:
import string

def remove_punc(txt) :
    return txt.translate(str.maketrans('','',string.punctuation))

In [67]:
df['texts'] = df['texts'].apply(remove_punc)

In [68]:
def remove_nums(txt):
    new=''
    for i in txt:
        if not i.isdigit():
            new += i
    return new

In [69]:
df['texts'] = df['texts'].apply(remove_nums)

In [70]:
def remove_emojis(txt):
    new=''
    for i in txt:
        if i.isascii():
            new += i
    return new

df['texts'] = df['texts'].apply(remove_emojis)

In [71]:
import nltk

In [72]:
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

In [73]:
nltk.download('punkt')
nltk.download('stopwords')
nltk.download("punkt_tab")

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\pankaj\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\pankaj\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\pankaj\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

True

In [74]:
stop_words = set(stopwords.words('english'))

In [75]:
df.loc[1]['texts']

'i can go from feeling so hopeless to so damned hopeful just from being around someone who cares and is awake'

In [76]:
def remove_stop_words(txt):
    words = word_tokenize(txt)
    cleaned = []
    for i in words:
        if not i in stop_words:
            cleaned.append(i)

    return ' '.join(cleaned)

In [77]:
df['texts'] = df['texts'].apply(remove_stop_words)

In [78]:
df.loc[1]['texts']

'go feeling hopeless damned hopeful around someone cares awake'

In [79]:
df.head()

                                               texts  emotions
0                              didnt feel humiliated         0
1  go feeling hopeless damned hopeful around some...         0
2          im grabbing minute post feel greedy wrong         1
3  ever feeling nostalgic fireplace know still pr...         2
4                                    feeling grouchy         1

In [80]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(df['texts'], df['emotions'], test_size=0.20, random_state=42)

In [81]:
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer

from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score, classification_report

bow_vectorizer = CountVectorizer()
X_train_bow = bow_vectorizer.fit_transform(X_train)
X_test_bow = bow_vectorizer.transform(X_test)

In [82]:
nb_model = MultinomialNB()
nb_model.fit(X_train_bow, y_train)

MultinomialNB()

In [83]:
pred_bow = nb_model.predict(X_test_bow)
print(accuracy_score(y_test, pred_bow))
print(classification_report(y_test, pred_bow))

0.7678125
              precision    recall  f1-score   support

           0       0.75      0.95      0.84       946
           1       0.89      0.63      0.74       427
           2       0.93      0.26      0.41       296
           3       1.00      0.05      0.10       113
           4       0.85      0.57      0.68       397
           5       0.73      0.96      0.83      1021

    accuracy                           0.77      3200
   macro avg       0.86      0.57      0.60      3200
weighted avg       0.80      0.77      0.74      3200

In [84]:
pred_bow

array([0, 5, 0, ..., 5, 5, 0], shape=(3200,))

In [85]:
tfidf_vectorizer = TfidfVectorizer()
X_train_tfidf = tfidf_vectorizer.fit_transform(X_train)
X_test_tfidf = tfidf_vectorizer.transform(X_test)


nb2_model = MultinomialNB()
nb2_model.fit(X_train_tfidf,y_train)

MultinomialNB()

In [86]:
y_pred_tfidf = nb2_model.predict(X_test_tfidf)

In [87]:
print(accuracy_score(y_test, y_pred_tfidf))
print(classification_report(y_test, y_pred_tfidf))

0.6609375
              precision    recall  f1-score   support

           0       0.70      0.93      0.80       946
           1       0.93      0.29      0.44       427
           2       1.00      0.03      0.06       296
           3       1.00      0.01      0.02       113
           4       0.92      0.22      0.36       397
           5       0.60      0.99      0.74      1021

    accuracy                           0.66      3200
   macro avg       0.86      0.41      0.40      3200
weighted avg       0.76      0.66      0.58      3200

In [88]:
from sklearn.linear_model import LogisticRegression

In [89]:
logistic_model = LogisticRegression(max_iter=1000)

In [90]:
logistic_model.fit(X_train_tfidf,y_train)

LogisticRegression(max_iter=1000)

In [91]:
log_pred = logistic_model.predict(X_test_tfidf)

In [92]:
print(accuracy_score(y_test, log_pred))
print(classification_report(y_test, log_pred))

0.8615625
              precision    recall  f1-score   support

           0       0.90      0.94      0.92       946
           1       0.90      0.81      0.86       427
           2       0.90      0.61      0.72       296
           3       0.88      0.47      0.61       113
           4       0.86      0.76      0.80       397
           5       0.81      0.96      0.88      1021

    accuracy                           0.86      3200
   macro avg       0.88      0.76      0.80      3200
weighted avg       0.87      0.86      0.86      3200

In [93]:
from sklearn.svm import LinearSVC, SVC

svm_model1 = LinearSVC()
svm_model1.fit(X_train_tfidf,y_train)

LinearSVC()

In [94]:
svm_pred1 = svm_model1.predict(X_test_tfidf)

In [95]:
print(accuracy_score(y_test, svm_pred1))
print(classification_report(y_test, svm_pred1))

0.891875
              precision    recall  f1-score   support

           0       0.93      0.93      0.93       946
           1       0.89      0.88      0.88       427
           2       0.83      0.74      0.78       296
           3       0.88      0.70      0.78       113
           4       0.87      0.85      0.86       397
           5       0.89      0.94      0.91      1021

    accuracy                           0.89      3200
   macro avg       0.88      0.84      0.86      3200
weighted avg       0.89      0.89      0.89      3200

In [ ]:
svm_model2 = SVC(
    kernel="linear",
    probability=True,
    random_state=42
)

In [97]:
svm_model2.fit(X_train_tfidf,y_train)

c:\Machine learning\venv\Lib\site-packages\sklearn\svm\_base.py:239: FutureWarning: The `probability` parameter was deprecated in 1.9 and will be removed in version 1.11. Use `CalibratedClassifierCV(SVC(), ensemble=False)` instead of `SVC(probability=True)`
  warnings.warn(

SVC(kernel='linear', probability=True)

In [98]:
svm_pred2 = svm_model2.predict(X_test_tfidf)

In [99]:
print(accuracy_score(y_test, svm_pred2))
print(classification_report(y_test, svm_pred2))

0.883125
              precision    recall  f1-score   support

           0       0.93      0.93      0.93       946
           1       0.89      0.88      0.88       427
           2       0.83      0.71      0.76       296
           3       0.81      0.65      0.73       113
           4       0.84      0.84      0.84       397
           5       0.88      0.94      0.91      1021

    accuracy                           0.88      3200
   macro avg       0.86      0.82      0.84      3200
weighted avg       0.88      0.88      0.88      3200

In [100]:
import pickle

pickle.dump(svm_model2, open("svm_model.pkl", "wb"))

In [101]:
pickle.dump(tfidf_vectorizer, open("tfidf_vectorizer.pkl", "wb"))

In [102]:
number_emotion = {v:k for k,v in emotion_number.items()}

pickle.dump(number_emotion, open("label_map.pkl","wb"))

In [103]:
pickle.dump(emotion_number, open("emotion_map.pkl", "wb"))

In [104]:
print(emotion_number)
print(df["emotions"].unique())
print(df["emotions"].value_counts().sort_index())

{'sadness': 0, 'anger': 1, 'love': 2, 'surprise': 3, 'fear': 4, 'joy': 5}
[0 1 2 3 4 5]
emotions
0    4666
1    2159
2    1304
3     572
4    1937
5    5362
Name: count, dtype: int64